### ISSUE TITLE
Core dump is thrown in lthread_compute_end()

### ISSUE THREAD

**Issue by swapi** [halayli/lthread#10]
When I tried to run example program (webserver.c), it crashes with core dump.
With gdb program halts at following:

```
Program received signal SIGSEGV, Segmentation fault.
0x001352ea in lthread_compute_end () at lthread_compute.c:126
126     asm("movl %0, 0(%%ebp)\n" ::"a"(lt->ebp));
```

Library and program compiled on `Linux 3.0.0-16-generic #29-Ubuntu SMP i686 i686 i386 GNU/Linux`

**Comment by jannson** [comment]
when using -DNDEBUG, it cause core dump because of
lthread.c:441 lt->sched->ready is null.

**Comment by jannson** [comment]
when using -DNDEBUG
the line in lthread.c like
    assert(pthread_key_create(&lthread_sched_key,
        _lthread_key_destructor) == 0);

will be ignored. some the code is error and cause core dump.
