### ISSUE TITLE
ucontext compat layer?

### ISSUE THREAD

**Issue by nwmcsween** [halayli/lthread#15]
Hi would lthread be able to provide a ucontext compat layer? This is needed for libcs that don't provide ucontext

**Comment by jannson** [comment]
Thanks, I will have a try for ucontext

**Comment by jannson** [comment]
I have to rewrite _lthread_init / _switch 
is it right ?

**Comment by jannson** [comment]
Thanks for your great works.
After try for hours, it finally works for arm.
This is my fork: https://github.com/jannson/lthread/commit/48ca55d19850c763e92659ffd271dae0ce0d5efc

Please have a check, if there are some errors I can found. I  will make the code better and give you a pull request, if you want to support for arm.
